# Generated by Django 3.0.14 on 2021-04-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='namedate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
