# Generated by Django 3.0.14 on 2021-04-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_namedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='namedate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
