# Generated by Django 3.0.3 on 2020-09-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200917_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('pa', 'Packed'), ('s', 'Shipped'), ('d', 'Delivered')], default='p', max_length=10),
        ),
    ]
