# Generated by Django 3.0.14 on 2021-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'COD'), ('PayTm', 'PayTm')], default='COD', max_length=10),
        ),
    ]
