# Generated by Django 3.0.3 on 2021-04-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
