# Generated by Django 3.0.3 on 2021-04-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
